OCAMLMAKEFILE = ./OCamlMakefile

SOURCES = charReader.mli charReader.ml 
SOURCES += report.mli report.ml
SOURCES += tokens.mli tokens.ml
SOURCES += scanner.mli scanner.ml
SOURCES += ast.ml
SOURCES += print.mli print.ml
SOURCES += parser.mli parser.ml
SOURCES += analyser.mli analyser.ml
SOURCES += generator.mli generator.ml
SOURCES += main.ml
RESULT  = dreic

include $(OCAMLMAKEFILE)
